### ISSUE TITLE
Errors in equality check

### ISSUE THREAD

**Issue by wtakuo** [psg-titech/emfrp-repl#4]
Equality and inequality operators do not work with non-integer data.
```
emfrp: (1, 2) == (1, 2)
((1, 2) = (1, 2))
machine_exec failure(16): Type Mismatch
Type Mismatch
=== EXECUTION LIST ===
======================
```
This may be due to the following line in the functions `exec_ast_equal` and `exec_ast_not_equal` (in `src/vm/exec.c`).
```
if(!object_is_integer(rro)) return EM_RESULT_TYPE_MISMATCH;
```
However, deleting the above line results in the following error.
```
emfrp: (1, 2) == (1, 2)
((1, 2) = (1, 2))
zsh: segmentation fault  ./emfrp-repl
```
The function `exec_equal` tries to take the `object_kind` of its argument even if it is `nullptr`, which causes a segmentation fault.
When comparing tuples, this occurs when the tags of the tuples are nullptr.

In addition, the following error also occurs
```
emfrp: true == 1
(true = 1)
zsh: segmentation fault  ./emfrp-repl
```
This is due to the way `object_true` and `object_false` are created. They are allocated (in `object_t.c`) but never initialized.

**Comment by puyogo-suzuki** [comment]
I fixed before PPL, but it is not committed yet.
Currently, I'm working on creating commits, sorry.

**Comment by puyogo-suzuki** [comment]
Fixed. bf22ee17b3918980f7acc9a50458313a877a2edc
